### ISSUE TITLE
Fails to build with openssl-3.0

### ISSUE THREAD

**Issue by shartge** [radsecproxy/radsecproxy#70]
Debian will be transitioning to openssl-3.0 for the next release soonish.

During testing I found that radsecproxy fails to build:

```
gcc -g -Wall -Werror -fno-strict-aliasing -I/usr/include -I/usr/include/openssl -Wall -pedantic -Wno-long-long -pthread -DRADPROT_UDP -DRADPROT_TCP -DRADPROT_TLS -DRADPROT_DTLS -g -O2 -fdebug-prefix-map=/build/radsecproxy-1.8.2=. -fstack-protector-strong -Wformat -Werror=format-security  -Wl,-z,relro -Wl,-z,now -o radsecproxy-conf catgconf.o debug.o gconfig.o util.o  -lnettle 
tlscommon.c: In function 'cookie_calculate_hash':
tlscommon.c:167:5: error: 'HMAC' is deprecated [-Werror=deprecated-declarations]
  167 |     HMAC(EVP_sha256(), (const void*) cookie_secret, COOKIE_SECRET_LENGTH,
      |     ^~~~
In file included from /usr/include/openssl/opensslv.h:109,
                 from /usr/include/openssl/macros.h:11,
                 from /usr/include/x86_64-linux-gnu/openssl/opensslconf.h:14,
                 from /usr/include/openssl/macros.h:10,
                 from /usr/include/openssl/ssl.h:16,
                 from tlscommon.c:25:
/usr/include/openssl/hmac.h:45:1: note: declared here
   45 | DEPRECATEDIN_3_0(unsigned char *HMAC(const EVP_MD *evp_md, const void *key,
      | ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

```
As a workaround I could remove the error on deprecations but a real fix would be nice.

**Comment by fmauchle** [comment]
If I read correctly, openssl has fixed this on their side: openssl/openssl#14628

**Comment by shartge** [comment]
I will rerun my tests and check if openssl3.0.0~beta1 has the PR merged and fixes this problem here.

**Comment by shartge** [comment]
For Openssl 3.0.0~beta1 currently in Debian Experimental, the errors now changed to this:

```
tlscommon.c: In function 'conftls_cb':
tlscommon.c:923:13: error: 'PEM_read_DHparams' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  923 |             conf->dhparam = PEM_read_DHparams(dhfp, NULL, NULL, NULL);
      |             ^~~~
In file included from /usr/include/openssl/ssl.h:36,
                 from tlscommon.c:25:
/usr/include/openssl/pem.h:469:1: note: declared here
  469 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, DHparams, DH)
      | ^~~~~~~~~~~~~~~~~~~
tlscommon.c:967:5: error: 'DH_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  967 |     DH_free(conf->dhparam);
      |     ^~~~~~~
In file included from /usr/include/openssl/dsa.h:51,
                 from /usr/include/openssl/x509.h:37,
                 from /usr/include/openssl/ssl.h:31,
                 from tlscommon.c:25:
/usr/include/openssl/dh.h:200:28: note: declared here
  200 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
cc1: all warnings being treated as errors
```

**Comment by robert-scheck** [comment]
Building radsecproxy 1.9.0 with OpenSSL 3.0.0 on Fedora Rawhide ("Fedora 36") fails like this:

```
[…]
gcc -DPACKAGE_NAME=\"radsecproxy\" -DPACKAGE_TARNAME=\"radsecproxy\" -DPACKAGE_VERSION=\"1.9.0\" -DPACKAGE_STRING=\"radsecproxy\ 1.9.0\" -DPACKAGE_BUGREPORT=\"https://radsecproxy.github.io\" -DPACKAGE_URL=\"\" -DPACKAGE=\"radsecproxy\" -DVERSION=\"1.9.0\" -DHAVE_MALLOPT=1 -DHAVE_LIBNETTLE=1 -DUSE_OPENSSL=1 -I.  -DSYSCONFDIR=\"/etc\"  -g -Wall -Werror -fno-strict-aliasing -I/usr/include -I/usr/include/openssl -Wall -pedantic -Wno-long-long -pthread -DRADPROT_UDP -DRADPROT_TCP -DRADPROT_TLS -DRADPROT_DTLS -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o tlscommon.o tlscommon.c
tlscommon.c: In function 'conftls_cb':
tlscommon.c:923:13: error: 'PEM_read_DHparams' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  923 |             conf->dhparam = PEM_read_DHparams(dhfp, NULL, NULL, NULL);
      |             ^~~~
In file included from /usr/include/openssl/ssl.h:36,
                 from tlscommon.c:25:
/usr/include/openssl/pem.h:469:1: note: declared here
  469 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, DHparams, DH)
      | ^~~~~~~~~~~~~~~~~~~
tlscommon.c:967:5: error: 'DH_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  967 |     DH_free(conf->dhparam);
      |     ^~~~~~~
In file included from /usr/include/openssl/dsa.h:51,
                 from /usr/include/openssl/x509.h:37,
                 from /usr/include/openssl/ssl.h:31,
                 from tlscommon.c:25:
/usr/include/openssl/dh.h:200:28: note: declared here
  200 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:643: tlscommon.o] Error 1
```

**Comment by fmauchle** [comment]
Should now be fixed in master branch. Please verify.

**Comment by shartge** [comment]
Will this fix be pulled into maint-1.9 and a new 1.9.x release be done soonish or should I just carry the patch locally for Debian for the upcoming openssl-3.0 transition?
